export enum InvestmentSubType {
  // FIXED_INCOME
  CRI = 'CRI',
  CRA = 'CRA',
  LCI = 'LCI',
  LCA = 'LCA',
  LC = 'LC',
  TREASURY = 'TREASURY',
  DEBENTURES = 'DEBENTURES',
  CDB = 'CDB',
  LIG = 'LIG',
  LF = 'LF',

  // SECURITY
  RETIREMENT = 'RETIREMENT',
  PGBL = 'PGBL',
  VGBL = 'VGBL',

  // MUTUAL_FUND
  INVESTMENT_FUND = 'INVESTMENT_FUND',
  STOCK_FUND = 'STOCK_FUND',
  MULTIMARKET_FUND = 'MULTIMARKET_FUND',
  EXCHANGE_FUND = 'EXCHANGE_FUND',
  FIXED_INCOME_FUND = 'FIXED_INCOME_FUND',
  FIP_FUND = 'FIP_FUND',
  OFFSHORE_FUND = 'OFFSHORE_FUND',
  ETF_FUND = 'ETF_FUND',

  // EQUITY
  STOCK = 'STOCK',
  BDR = 'BDR',
  REAL_ESTATE_FUND = 'REAL_ESTATE_FUND',
  DERIVATIVES = 'DERIVATIVES',
  OPTION = 'OPTION',

  // ETF
  ETF = 'ETF',

  // COE
  STRUCTURED_NOTE = 'STRUCTURED_NOTE',
}
